### ISSUE TITLE
Scraping: Infogob Historial de Militancia

### ISSUE THREAD

**Issue by gianpietro1** [openpolitica/jne-elecciones#15]
Esta información sería muy valiosa para poder mostrar qué candidatos estuvieron en partidos anteriores.

**Comment by jeqo** [comment]
@gianpietro1 tenemos los enlaces y ejemplos para trabajar en esta fuente?

**Comment by gianpietro1** [comment]
@jeqo sí aquí van:

Enlace base: https://infogob.jne.gob.pe/Politico/
...pero al buscar por nombre o DNI, hay un par de enlaces consultados:

https://infogob.jne.gob.pe/Politico/FichaPolitico/daniel-enrique-salaverry-villa_historial-partidario_cXj8+EEqgjgc6+@0ElOxMA==jE

https://infogob.jne.gob.pe/Politico/FichaPolitico/richard-felix-martinez-guerra_historial-partidario_qewCJYZGW0k=wY

Quizá podríamos usar todos los id_dni de la DB y recorrer, pero no he encontrado como armar la URL en base al nombre

**Comment by jeqo** [comment]
@gianpietro1 espero comenzar a trabajar en esto el viernes. sorry por la demora.

**Comment by gianpietro1** [comment]
> @gianpietro1 espero comenzar a trabajar en esto el viernes. sorry por la demora.

gracias @jeqo, no hay problema.
