### ISSUE TITLE
Aparecen dos entradas en afiliaciones cuando en la página original solo hay una

### ISSUE THREAD

**Issue by LuighiV** [openpolitica/jne-elecciones#19]
En el dataset se muestra esta información:
https://openpolitica-jne-dtnlgurdna-rj.a.run.app/2021-militancia-candidatos-congresales/afiliacion?_sort=rowid&dni__exact=8236035
donde únicamente difieren en afiliacion_comite

En la página correspondiente solo aparece una afiliación:
https://infogob.jne.gob.pe/Politico/FichaPolitico/alejandro-aurelio-aguinaga-recuenco_historial-partidario_XLqpCWICcEM=qW

Lo que sí, aparecen dos cargos, pero esa información no está siendo extraída (aunque sería bueno también contar con esa información).

**Comment by jeqo** [comment]
@LuighiV me confirmas si el error persiste para reabrir el issue.

**Comment by LuighiV** [comment]
En lo que he verificado, no se ha presentado. Si con alguno se presenta nuevamente, te aviso. Gracias :)
