### ISSUE TITLE
Revisar variables no integradas

### ISSUE THREAD

**Issue by gianpietro1** [openpolitica/jne-elecciones#8]
El siguiente enlace (segunda hoja) contiene variables que potencialmente nos pueden interesar (nos están asesorando para ver cuáles son más relevantes).
https://docs.google.com/spreadsheets/d/1u7HAyNXvNbZeLCCijBQ5Svdg-0dmBDMxEXak9JImr0A/edit#gid=1832662856

Abro el issue con el objetivo de explorar la complejidad de obtener esa información de manera programática.

**Comment by jeqo** [comment]
https://d1ts5g4ys243sh.cloudfront.net/proyectos_especiales_prod/especiales/elecciones-2021-lista-candidatos-presidencia-congreso-parlamento-andino-tu-decides-nndd-ecvisual-ecpm/xlsx/2021_candidatos_presidenciales_perfiles.xlsx

**Comment by jeqo** [comment]
https://d1ts5g4ys243sh.cloudfront.net/proyectos_especiales_prod/especiales/elecciones-2021-lista-candidatos-presidencia-congreso-parlamento-andino-tu-decides-nndd-ecvisual-ecpm/xlsx/2021_candidatos_congresales_perfiles.xlsx

**Comment by jeqo** [comment]
Mientras se puedan descargar directamente del sitio no debe haber necesidad de implementar procesos de extraccion. 
![image](https://user-images.githubusercontent.com/6180701/105640895-b1fa7600-5e78-11eb-8a7f-3158da4ef3c1.png)
